config/routes.rb
Rails.application.routes.draw do

  get 'authentications/index'

  get 'welcome/index'
  resources :articles

get 'tags/:tag', to: 'articles#index', as: :tag

   
   root 'welcome#index'

get 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
get 'auth/failure', to: redirect('/')
get 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/article.rb
class Article < ActiveRecord::Base
 
acts_as_taggable

has_attached_file :pic, :styles => 
          { :medium => "300x300>", :thumb => "100x100>" }

validates_attachment_content_type :pic, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.search(query)
    # where(:title, query) 
    where("title like ?", "%#{query}%") 
  end

end

app/models/user.rb
class User < ActiveRecord::Base

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.provider = auth.provider 
    user.uid      = auth.uid
    user.name     = auth.info.name
    user.save
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end


 def show
    @article = Article.find(params[:id])
  end

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    elsif params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC")
    else
      @articles = Article.order("created_at DESC")
    end
  end


def create
  @article = Article.new(article_params)
  @article.save
  redirect_to @article
end
 
private
  def article_params
    params.require(:article).permit(:title, :text, :costo, :email, :direccion, :pic, :tag_list)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</div>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Smart Shopping</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="css/styles.css" rel="stylesheet">
	</head>
	<body>
<header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/articles/" class="navbar-brand">Inicio</a>
    </div>
    


<nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="/articles/new/">Publicar</a>
        </li>
        <li>
          <a href="#">Mis anuncios</a>
        </li>
        <li>
          <a href="#">Ajustes</a>
        </li>
      </ul>

      <ul class="nav navbar-right navbar-nav">
        <li class="dropdown">

          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i></a>

          <ul class="dropdown-menu" style="padding:12px;">
<%= form_tag(articles_path, :method => "get", class: "navbar-form", id: "search-form") do %>
            <form class="form-inline">
              <button type="submit" class="btn btn-default pull-right"><i class="icon-search"></i></button>
		<%= text_field_tag :search, params[:search], class: "form-control pull-left", placeholder: "Buscar archivo" %>
  <% end %>
  <%= yield %>
            </form>
          </ul>
        </li>
      </ul>

    </nav>

	
  </div>
</header>


<div id="masthead">  
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>Smart Shopping 
          <p class="lead"></p>
        </h1>
      </div>
      <div class="col-md-5">
        <div class="well well-lg"> 
          <div class="row">
            <div class="col-sm-12">
                <h2>Artículos</h2>   
			
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="top-spacer"> </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
</div>


<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">


<!--Publicaciones-->
<h1>Últimas publicaciones</h1>
 
<table>
 
  <% @articles.each do |article| %>
    <tr>


       <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">

<%= image_tag article.pic.url %>

            </div>
            <div class="col-md-10 col-sm-9">
              <h3>Nombre del producto: <%= article.title %> </h3>

	     <%= article.text %>

		
              <div class="row">
                <div class="col-xs-9">
                  <h4><span class="label label-default"><%= @nickname%></span></h4><h4>
                  <small style="font-family:courier,'new courier';" class="text-muted"><%= article.updated_at %>  • <a href="#" class="text-muted">Like </a></small>
                  </h4></div>
                <div class="col-xs-3"></div>
              </div>

<a href="/articles/<%= article.id %>/" class="btn btn-primary pull-right btnNext">Ver</a>
              <br><br>
            </div>
          </div>

          <hr>
    </tr>
  <% end %>
</table>



<!--Publicaciones-->
 

          
          

        

</div>
      </div>
                                                                                       
	                                                
                                                 
   	</div><!--/col-12-->
  </div>
</div>
                                                
                                                                                
<hr>



<div class="container" id="footer">
<div id="tag_cloud">
<h1> Tags: </h1> 
  <% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>
</div>

<hr>


	<!-- script references -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
	</body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Smart Shopping</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="css/styles.css" rel="stylesheet">
	</head>
	<body>
<header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/articles/" class="navbar-brand">Inicio</a>
    </div>
    


<nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="/articles/new/">Publicar</a>
        </li>
        <li>
          <a href="#">Mis anuncios</a>
        </li>
        <li>
          <a href="#">Ajustes</a>
        </li>
      </ul>

      <ul class="nav navbar-right navbar-nav">
        <li class="dropdown">

          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i></a>

          <ul class="dropdown-menu" style="padding:12px;">
<%= form_tag(articles_path, :method => "get", class: "navbar-form", id: "search-form") do %>
            <form class="form-inline">
              <button type="submit" class="btn btn-default pull-right"><i class="icon-search"></i></button>
		<%= text_field_tag :search, params[:search], class: "form-control pull-left", placeholder: "Buscar archivo" %>
  <% end %>
  <%= yield %>
            </form>
          </ul>
        </li>
      </ul>

    </nav>

	
  </div>
</header>

<div id="masthead">  
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>Smart Shopping 
          <p class="lead"></p>
        </h1>
      </div>
      <div class="col-md-5">
        <div class="well well-lg"> 
          <div class="row">
            <div class="col-sm-12">
                <h2>Publicar artículo</h2>   
			
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="top-spacer"> </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
</div>


<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">


<!--Formulario-->
<h2> Formulario de publicación </h2>

<%= form_for @article, :html => { :multipart => true } do |f| %>

  <p>
    <%= f.label :Titulo%><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Descripcion%><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :Costo %><br>
    <%= f.text_field :costo %>
  </p>

  <p>
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :Locacion%><br>
    <%= f.text_field :direccion %>
  </p>

 
  <p>
    <%= f.label :Seleccionar_foto%>
    <%= f.file_field :pic %>
  </p>


  <p>
    <%= f.label :tag_list_separados_por_comas%> <br>
    <%= f.text_field :tag_list %>
  </p>



<button type="submit" class="btn btn-primary pull-right btnNext">Publicar </button>


<% end %>


</div>
      </div>
                                                                                       
	                                                

                                                
                                                                                
<hr>





	<!-- script references -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
	</body>
</html>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Smart Shopping</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="css/styles.css" rel="stylesheet">
	</head>
	<body>
<header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/articles/" class="navbar-brand">Inicio</a>
    </div>
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="/articles/new/">Publicar</a>
        </li>
        <li>
          <a href="#">Mis anuncios</a>
        </li>
        <li>
          <a href="#">Ajustes</a>
        </li>
      </ul>

      <ul class="nav navbar-right navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-search"></i></a>
          <ul class="dropdown-menu" style="padding:12px;">
            <form class="form-inline">
              <button type="submit" class="btn btn-default pull-right"><i class="glyphicon glyphicon-search"></i></button>
		<input type="text" class="form-control pull-left" placeholder="Buscar archivo">
            </form>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

<div id="masthead">  
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>Smart Shopping 
          <p class="lead"></p>
        </h1>
      </div>
      <div class="col-md-5">
        <div class="well well-lg"> 
          <div class="row">
            <div class="col-sm-12">
                <h2>Publicación</h2>   
			
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="top-spacer"> </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
</div>


<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">




<!--Publicaciones-->
<h1><%= @article.title %></h1>

<hr>

 <center>
<%= image_tag @article.pic.url %>
</center>


<hr>
<p>
   <strong>Descripcion:</strong>
  <%= @article.text %>
</p>






<p>
   <strong>Direccion:</strong>
  <%= @article.direccion %>
</p>



<p>
   <strong>Precio:</strong>
  <%= @article.costo %>
</p>

<p>
  <strong>Hora de publicación:</strong>
  <%= @article.updated_at %>
</p>



<hr>


<p>
  <strong>Relacionados:</strong>
<%= raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
</p>



<!--Publicaciones-->
 

          
          

        

</div>
      </div>
                                                                                       
	                                                
  </div>
</div>
                                                


	<!-- script references -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smartshopping</title>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


<div class="container" id="footer">
  <div class="row">
    <div class="col col-sm-12">
      
      <h1>Follow Us</h1>
      <div class="btn-group">
       <a class="btn btn-twitter btn-lg" href="https://twitter.com/SmartShoppingMO"><i class="icon-twitter icon-large"></i> Twitter</a>
	   <a class="btn btn-facebook btn-lg" href="https://www.facebook.com/smartshoppingMO"><i class="icon-facebook icon-large"></i> Facebook</a>
	   <!---a class="btn btn-google-plus btn-lg" href="#"><i class="icon-google-plus icon-large"></i> Google+</a> -->
      </div>
      
    </div>
  </div>
</div>

<hr>



<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %> <br>
    <%= link_to "Sign in with Twitter",  "/auth/twitter", id: "sign_in" %>
  <% end %>
</div>


<hr>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <ul class="list-inline">
          <li><i class="icon-facebook icon-2x"></i></li>
          <li><i class="icon-twitter icon-2x"></i></li>
          <li><i class="icon-google-plus icon-2x"></i></li>
          <li><i class="icon-pinterest icon-2x"></i></li>
        </ul>
        
      </div>

    </div>
  </div>
</footer>




</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Smart Shopping</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="css/styles.css" rel="stylesheet">
	</head>
	<body>
<header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/articles/" class="navbar-brand">Inicio</a>
    </div>
    


<nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="/articles/new/">Publicar</a>
        </li>
        <li>
          <a href="#">Mis anuncios</a>
        </li>
        <li>
          <a href="#">Ajustes</a>
        </li>
      </ul>

      <ul class="nav navbar-right navbar-nav">
        <li class="dropdown">

          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i></a>

          <ul class="dropdown-menu" style="padding:12px;">
<%= form_tag(articles_path, :method => "get", class: "navbar-form", id: "search-form") do %>
            <form class="form-inline">
              <button type="submit" class="btn btn-default pull-right"><i class="icon-search"></i></button>
		<%= text_field_tag :search, params[:search], class: "form-control pull-left", placeholder: "Buscar archivo" %>
  <% end %>
  <%= yield %>
            </form>
          </ul>
        </li>
      </ul>

    </nav>

	
  </div>
</header>

<div id="masthead">  
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>Smart Shopping 
          <p class="lead"></p>
        </h1>
      </div>
      <div class="col-md-5">
        <div class="well well-lg"> 
          <div class="row">
            <div class="col-sm-12">
              <h3>Piensa Inteligente,piensa en  <img alt="" src="assets/logow.png" style="width:75stopx;height:75px" hspace="20"></a>     </h3>	 <a class="story-title" href="#" >
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="top-spacer"> </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
</div>



<div class="container">
  <div class="row">
    <div class="col-md-12"> 
      <div class="panel">
        <div class="panel-body">

      <a class="story-title" href="#"><img alt="" src="assets/init.png "></a>
          <button type="button" class="btn-twitter btn-lg"> <i class="icon-twitter" ><img alt="" hspace="10"></i>Sign in with Twitter</button>
           <button type="button" class="btn-facebook btn-lg"> <i class="icon-facebook" hspace="10"></i>Sign in with Facebook</button>
        </div>
         </div>
      </div>
      </div>
   </div> 
</div>                                                                      
<hr>





	<!-- script references -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>



	</body>
</html>